### ISSUE TITLE
How do we solve component depedency problem in this architecture ?

### ISSUE THREAD

**Issue by samir-byte** [przemek-nowicki/node-express-template.ts#4]
Let's say i have token.model.ts and user.model.ts and i need two components lets say auth and user. How do i manage that flow. Is it okay to share database model and services between different components ?

**Comment by przemek-nowicki** [comment]
> Let's say i have token.model.ts and user.model.ts and i need two components lets say auth and user. How do i manage that flow. Is it okay to share database model and services between different components ?

@samir-byte Yes, it's okay to share database models and services between different components. It's actually a very common practice. You might also place such shared models or services in a "shared" or "common" directory:

As always, there's no one-size-fits-all structure for every project. What works best really depends on what your project needs. However, one important tip from the Node.js Best Practices guide is to organize your files based on what they do like features or functionality instead of the technical stuff like controllers, views, or models.

You can also check this out for some inspiration for your solution: 
https://github.com/goldbergyoni/nodebestpractices/blob/master/sections/projectstructre/breakintcomponents.md
